[u] Rename _preauth to _login, _deauth to _logout

diff --git a/environment b/environment
--- a/environment
+++ b/environment
@@ -19,10 +19,10 @@ _select() {
 	else
 		if ! {
 			_validate_link "$1" &&
-			_deauth &&
+			_logout &&
 			_link "$1" &&
 			_refresh &&
-			_preauth ;
+			_login ;
 		} ; then
 			echo >&2 "_select failed"
 			return 1
@@ -32,7 +32,7 @@ _select() {
 
 _deselect() {
 	if ! {
-		_deauth &&
+		_logout &&
 		_unlink &&
 		_refresh ;
 	} ; then
@@ -70,14 +70,14 @@ _show_link() {
 	( cd "${project_root}/deployments" && ls -l .active )
 }
 
-_preauth_google() {
+_login_google() {
 	if [ -n "$azul_google_user" ] ; then
 		if ! {
 			gcloud auth login --update-adc --quiet "$azul_google_user" &&
 			gcloud config set project "$GOOGLE_PROJECT" &&
 			gcloud auth application-default set-quota-project "$GOOGLE_PROJECT" ;
 		} ; then
-			echo >&2 "_preauth_google failed"
+			echo >&2 "_login_google failed"
 			return 1
 		fi
 	fi
@@ -89,7 +89,7 @@ _preauth_google() {
 #
 # https://github.com/boto/boto3/issues/1179#issuecomment-569940530
 #
-_preauth_aws() {
+_login_aws() {
 	local env
 	if ! env="$(
 		python - <<- "EOF"
@@ -125,13 +125,13 @@ _preauth_aws() {
 			print(f'export AWS_SESSION_TOKEN={credentials.token}')
 		EOF
 	)" ; then
-		echo >&2 "_preauth_aws failed"
+		echo >&2 "_login_aws failed"
 		return 1
 	fi
 	eval "$env"
 }
 
-_preauth_docker_ecr() {
+_login_docker_ecr() {
 	if [ -n "${azul_docker_registry:+x}" ] ; then
 		if ! (
 			set -o pipefail
@@ -141,13 +141,13 @@ _preauth_docker_ecr() {
 				--password-stdin \
 				"${azul_docker_registry%/}"
 		) ; then
-			echo >&2 "_preauth_docker_ecr failed"
+			echo >&2 "_login_docker_ecr failed"
 			return 1
 		fi
 	fi
 }
 
-_preauth_docker_gitlab() {
+_login_docker_gitlab() {
 	if {
 		[ -n "${azul_gitlab_access_token:+x}" ] &&
 		[ -n "${azul_gitlab_user:+x}" ] ;
@@ -160,89 +160,89 @@ _preauth_docker_gitlab() {
 				--password-stdin \
 				"docker.gitlab.${AZUL_DOMAIN_NAME}"
 		) ; then
-			echo >&2 "_preauth_docker_gitlab failed"
+			echo >&2 "_login_docker_gitlab failed"
 			return 1
 		fi
 	fi
 }
 
-_preauth() {
+_login() {
 	if {
-		_preauth_google &&
-		_preauth_aws &&
-		_preauth_docker_ecr &&
-		_preauth_docker_gitlab ;
+		_login_google &&
+		_login_aws &&
+		_login_docker_ecr &&
+		_login_docker_gitlab ;
 	} ; then
 		echo >&2 \
-			"Session credentials are in effect for AWS. Additionally, you have " \
-			"been logged into Google Cloud, Amazon ECR and the GitLab Docker " \
-			"registry. Use '_deauth' to invalidate the session credentials. " \
-			"Alternatively, you can use _deauth_completely to invalidate all " \
+			"Session credentials are in effect for AWS. Additionally, you have" \
+			"been logged into Google Cloud, Amazon ECR and the GitLab Docker" \
+			"registry. Use '_logout' to invalidate the session credentials." \
+			"Alternatively, you can use _logout_completely to invalidate all" \
 			"credentials but this is usually not necessary."
 	else
-		echo >&2 "_preauth failed"
+		echo >&2 "_login failed"
 		return 1
 	fi
 }
 
-_deauth_docker_ecr() {
+_logout_docker_ecr() {
 	if [ -n "${azul_docker_registry:+x}" ] ; then
 		if ! {
 			docker logout "${azul_docker_registry}" ;
 		} ; then
-			echo >&2 "_deauth_docker_ecr failed"
+			echo >&2 "_logout_docker_ecr failed"
 			return 1
 		fi
 	fi
 }
 
-_deauth_docker_gitlab() {
+_logout_docker_gitlab() {
 	if {
 		[ -n "${azul_gitlab_access_token:+x}" ] &&
 		[ -n "${azul_gitlab_user:+x}" ] ;
 	} ; then
 		if ! docker logout "docker.gitlab.${AZUL_DOMAIN_NAME}" ; then
-			echo >&2 "_deauth_docker_gitlab failed"
+			echo >&2 "_logout_docker_gitlab failed"
 			return 1
 		fi
 	fi
 }
 
-_deauth_aws() {
+_logout_aws() {
 	unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
 }
 
-_deauth_google() {
+_logout_google() {
 	if [ -n "$azul_google_user" ] ; then
 		if ! {
 			gcloud auth application-default revoke --quiet &&
 			gcloud auth revoke --quiet ;
 		} ; then
-			echo >&2 "_deauth_google failed"
+			echo >&2 "_logout_google failed"
 			return 1
 		fi
 	fi
 }
 
-_deauth() {
+_logout() {
 	# Docker segregates credential state by registry and we maintain separate
 	# registries (both ECR and GitLab) per deployment so we won't need to log out
 	# of those registries when switching deployments. Above, we offer dedicated
 	# functons for explicitly logging our of those registries.
-	_deauth_aws
+	_logout_aws
 	# We segregate Google state by deployment and working copy (see
 	# CLOUDSDK_CONFIG in environment.py) so we don't need to log out of Google
 	# when switching deployments. Above we offer a dedicated function for
 	# explicitly logging out of Google.
 }
 
-_deauth_completely() {
+_logout_completely() {
   # We don't use `&&` between function invocations because failing to log out of
   # one realm shouldn't prevent us from attempting to log out of the others.
-	_deauth_google
-	_deauth
-	_deauth_docker_ecr
-	_deauth_docker_gitlab
+	_logout_google
+	_logout
+	_logout_docker_ecr
+	_logout_docker_gitlab
 }
 
 _revenv() {
